src/proyectocursos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',TemplateView.as_view(template_name='base/home.html'), name='home'),
    path('cursos/', include('apps.cursos.url', namespace='cursos')),
    path('usuarios/',include('apps.usuarios.url',namespace='usuarios'))
]

src/apps/cursos/models.py
from datetime import date, time
from django.db import models
from django.db.models.base import Model
from django.db.models.fields.mixins import FieldCacheMixin
from apps.usuarios.models import Estudiante, Profesor

# Create your models here.
class curso(models.Model):
    MODALIDAD_OPCIONES = (
        ('virtual', 'Virtual'),
        ('presencial', 'Presencial'),
        ('mixto','Mixto')
    )
    ESTADO_OPCIONES = (
        ('en_revision','En Revision'),
        ('aprobado','Aprobado'),
        ('desaprobado','Desaprobado')
    )
    nombrecurso = models.CharField(max_length=100)
    objetivogeneral = models.TextField(max_length=5000)
    modalidad = models.CharField(max_length=10,choices=MODALIDAD_OPCIONES)
    costo = models.IntegerField()
    horascatedra = models.IntegerField()
    honorarios = models.DecimalField(max_digits=7,decimal_places=2,null=True,blank=True)
    cantidadminalumnos = models.IntegerField()
    cantidadmaxalumnos = models.IntegerField()
    fechaini = models.DateField()
    fechafin = models.DateField()
    docentecargo = models.ManyToManyField(Profesor)
    estadocurso = models.CharField(max_length=20,default='En Revision', choices=ESTADO_OPCIONES)
    motivo = models.TextField(max_length=1000,default='Sin Motivo')
    def __str__(self):
        return f"NombreCurso:{self.nombrecurso}"

#----------------------------------------------------------------------------------------    
class Pago(models.Model):
    # PAGO_OPCIONES = (
    #     ('Efectivo', 'Efectivo'),
    #     ('Tarjeta', 'Tarjeta'),
    #     ('Transferencia','Transferencia')
    # )
    formaPago = models.CharField( max_length=15)
    importe = models.DecimalField(max_digits=7,decimal_places=2)
    descripcion = models.TextField(max_length=250)
    fecha = models.DateTimeField(default= date.today)
    numRecibo = models.IntegerField(null=True,blank=True)
    curso = models.ForeignKey(curso, on_delete=models.CASCADE,null=True,blank=True)
    inscripto = models.ForeignKey(Estudiante, on_delete=models.CASCADE,null=True,blank=True)
    class Meta:
        abstract = True
    
class PagoEfectivo(Pago):
    formaPago= models.CharField(default='Efectivo',max_length=100)
    numeroTicket=models.IntegerField(null=True,blank=True)

class PagoTarjeta(Pago):
    PAGO_TARJETA_OPCIONES= (
        ('Debito', 'Debito'),
        ('Credito', 'Credito')    
    )
    titularTarjeta = models.CharField(max_length=50)
    numeroTarjeta = models.CharField(max_length=16)
    tipoTarjeta = models.CharField(choices=PAGO_TARJETA_OPCIONES,max_length=10)
    codSeguridad = models.CharField(max_length=3)
    fechaCaducidad = models.DateField()
    formaPago = models.CharField(default='PagoTarjeta',max_length=100)

class PagoTransferencia(Pago):
    CBU = models.CharField(max_length=22)
    alias = models.CharField(max_length=25)
    banco = models.CharField(max_length=50)
    formaPago = models.CharField(default='PagoTransferencia',max_length=100)

#-----------------------------------------------------------------------------

class Inscriptos(models.Model):
    curso = models.ForeignKey(curso, on_delete=models.CASCADE)
    inscripto = models.ForeignKey(Estudiante, on_delete=models.CASCADE)
    nota1 = models.IntegerField(null=True,blank=True,default = 0)
    nota2 = models.IntegerField(null=True,blank=True,default = 0)
    nota3 = models.IntegerField(null=True,blank=True,default = 0)
    asistencia = models.CharField(max_length=4, default='100%')

    def __str__(self):
        return f"El inscripto con el nombre {self.inscripto.nombreyapellido}" 

#Lo agregamos para una posible funcionalidad pero no la usamos
class Estadistica(models.Model):
    curso = models.ForeignKey(curso,on_delete=models.CASCADE)

src/apps/cursos/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.db.models import fields
from django.forms.widgets import DateInput

from apps.cursos.models import Estadistica, Inscriptos, PagoEfectivo, PagoTarjeta, PagoTransferencia, curso 

class cursoForm(forms.ModelForm):
    
    class Meta:
        model = curso
        fields = ("nombrecurso","objetivogeneral", "modalidad", "costo" ,"honorarios" ,"horascatedra","cantidadminalumnos","cantidadmaxalumnos","fechaini","fechafin","docentecargo")
    widgets = {
            'fechaini': DateInput(format='%Y-%m-%d', attrs={'type': 'date'}),
            'fechafin': DateInput(format='%Y-%m-%d', attrs={'type': 'date'})
        }

    def clean(self):
        datos_validados = super().clean()
        fecha_inicio = datos_validados['fechaini']
        fecha_fin = datos_validados['fechafin']
        cantmaxalu = datos_validados['cantidadmaxalumnos']
        cantminalu = datos_validados['cantidadminalumnos']
        
        if fecha_fin and fecha_inicio > fecha_fin:
            raise ValidationError(
                {'fechaini': 'La fecha de inicio no puede ser posterior a la fecha fin'}
            )

        if cantmaxalu < cantminalu:
            raise ValidationError(
                {'cantidadminalumnos': 'La cantidad minima de alumnos no puede ser mayor a la cantidad maxima'}
            )
   

        return datos_validados

class efectivoForm(forms.ModelForm):
    
    class Meta:
        model = PagoEfectivo
        fields = ("formaPago","importe","descripcion","fecha","numRecibo","numeroTicket","curso","inscripto")

class tarjetaForm(forms.ModelForm):
    
    class Meta:
        model = PagoTarjeta
        fields = ("formaPago","importe","descripcion","fecha","numRecibo","titularTarjeta","numeroTarjeta","tipoTarjeta","codSeguridad","fechaCaducidad","curso","inscripto")

   

class transferenciaForm(forms.ModelForm):

    class Meta:
        model = PagoTransferencia
        fields = ("formaPago","importe","descripcion","fecha","numRecibo","CBU","alias","banco","curso","inscripto")        

class inscripcionForm(forms.ModelForm):
    class Meta:
        model = Inscriptos
        fields = ("curso","inscripto","nota1","nota2","nota3","asistencia")

class estadisticaForm(forms.ModelForm):
    class Meta:
        model = Estadistica
        fields = ('curso',)

src/apps/cursos/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required, permission_required
from apps.cursos.forms import cursoForm, efectivoForm, estadisticaForm, inscripcionForm, tarjetaForm, transferenciaForm
from apps.usuarios.forms import estudianteForm
from apps.usuarios.models import Estudiante
from .models import PagoEfectivo, PagoTarjeta, PagoTransferencia, curso, Inscriptos,Pago
from apps.usuarios.models import Persona


# Create your views here.

@permission_required('cursos.view_curso', raise_exception=True)
def listaCursos(request):
    return render(request, 'cursos/tablaCursos.html',
                  {'cursos': curso.objects.all()})

@permission_required('cursos.add_curso', raise_exception=True)
def creacion_curso(request):
    if (request.method == 'POST'):
        curso_form = cursoForm(request.POST)
        if curso_form.is_valid():
            nuevo_curso = curso_form.save(commit=True)
            messages.success(request,
                             'Se ha agregado correctamente el Curso {}'.format(nuevo_curso))
            return redirect(reverse('cursos:estadoCursos'))
    else:
        curso_form = cursoForm()
    return render(request, 'cursos/formcrearcurso.html', {'form': curso_form})


@permission_required('cursos.change_curso', raise_exception=True)
def edicion_curso(request, pk):
    Curso = get_object_or_404(curso, pk=pk)

    if (request.method == 'POST'):
        curso_form = cursoForm(request.POST, request.FILES, instance=Curso)
        if curso_form.is_valid():
            curso_form.save(commit=True)
            messages.success(request,
                             'Se ha editado correctamente el curso con el {}'.format(Curso))
            return redirect(reverse('cursos:registroCursos'))
    else:
        curso_form = cursoForm(instance=Curso)
    return render(request, 'cursos/modificarCurso.html', {'form': curso_form})


@permission_required('cursos.add_group', raise_exception=True)
@permission_required('cursos.view_curso', raise_exception=True)
@permission_required('cursos.change_curso', raise_exception=True)
@permission_required('cursos.delete_curso', raise_exception=True)
def ventana_ecurso(request, pk):
    Curso = get_object_or_404(curso, pk=pk)
    return render(request,
                  'cursos/evaluacionCurso.html',
                  {'curso': Curso})


@permission_required('cursos.add_group', raise_exception=True)
@permission_required('cursos.view_curso', raise_exception=True)
@permission_required('cursos.change_curso', raise_exception=True)
@permission_required('cursos.delete_curso', raise_exception=True)
def evaluar_curso(request):
    if request.method == 'POST':
        if 'id_curso' in request.POST:
            Curso = get_object_or_404(curso, pk=request.POST['id_curso'])
            nombre_curso = Curso.nombrecurso
            Curso.motivo = request.POST['motivo']
            Curso.estadocurso = request.POST['estadocurso']
            Curso.save()
            messages.success(request, 'Se ha evaluado exitosamente el curso {}'.format(nombre_curso))
        else:
            messages.error(request, 'Debe indicar qué curso desea evaluar')
    return redirect(reverse('cursos:registroCursos'))


@permission_required('cursos.delete_curso', raise_exception=True)
def curso_delete(request):
    if request.method == 'POST':
        if 'id_curso' in request.POST:
            Curso = get_object_or_404(curso, pk=request.POST['id_curso'])
            nombre_curso = Curso.nombrecurso
            Curso.delete()
            messages.success(request, 'Se ha eliminado exitosamente el curso {}'.format(nombre_curso))
        else:
            messages.error(request, 'Debe indicar qué curso se desea eliminar')
    return redirect(reverse('cursos:registroCursos'))


# ----------------------------------------------------------------------------#
@permission_required('cursos.view_curso', raise_exception=True)
def datosCurso(request, pk):
    bandera = 0;
    pago = False
   
    Curso = get_object_or_404(curso, pk=pk)
    listaIns = Inscriptos.objects.all()
    if(request.user.first_name.lower() == 'alumno'):
        pagoefectivo = PagoEfectivo.objects.filter(inscripto=request.user.estudiante.id, curso= Curso.id)
        pagotarjeta = PagoTarjeta.objects.filter(inscripto=request.user.estudiante.id, curso= Curso.id)
        pagotransferencia =PagoTransferencia.objects.filter(inscripto=request.user.estudiante.id, curso= Curso.id)
        if(pagoefectivo or pagotarjeta or pagotransferencia):
            pago=True
            
        if(request.user.estudiante.id):
            for estudiante in listaIns:
                if(request.user.estudiante.id == estudiante.inscripto.id and Curso.id == estudiante.curso.id):
                    bandera = 1
                    break

    return render(request,
                  'cursos/datosCurso.html',
                  {'curso': Curso,'bandera': bandera,'pago':pago})

#----------------------------------------------------------------------------------------------------------------------------
@login_required
def estadisticas(request):
    return render(request, 'cursos/estadisticas.html', {'cursos':curso.objects.all()})
    
@login_required
def estadisticas_1(request):
    #if request.method == 'POST':
            Cursos = curso.objects.all()
            #Curso = get_object_or_404(curso,pk=request.POST['id_curso'])
            
            #cantinscriptos = []
            for data in Cursos:
                #cantinscriptos.append(len(Inscriptos.objects.filter(curso = data.id)))
                data.cant = len(Inscriptos.objects.filter(curso = data.id))
                 
            #print(cantinscriptos)
            return render(request,'cursos/estadisticascantinscriptos.html',{'cursos':Cursos})
            # nombre_curso = Curso.nombrecurso
            # Curso.delete()
            # messages.success(request, 'Se ha eliminado exitosamente el curso {}'.format(nombre_curso))
        # else:
            # messages.error(request, 'Debe indicar qué Programa se desea eliminar')
@login_required
def estadisticas_2(request):
    Cursos = curso.objects.all()
    
    for data in Cursos:
        data.cant = len(Inscriptos.objects.filter(curso = data.id))
        data.cantP= len(PagoEfectivo.objects.filter(curso = data.id)) + len(PagoTarjeta.objects.filter(curso = data.id)) + len(PagoTransferencia.objects.filter(curso = data.id)) 
        data.cantD= data.cant - data.cantP
    
    return render(request,'cursos/estadisticascantpago.html',{'cursos':Cursos})    


@login_required
def estadisticas_3(request):
    if request.method == 'POST':
        fechaini = request.POST.get('id_anioinicio',None)
        fechafin = request.POST.get('id_aniofin',None)
        intervalo= curso.objects.filter(fechaini__range=(fechaini, fechafin))
    return render (request,'cursos/listaCursosAnio.html',{'intervalo':intervalo,'fechaini':fechaini,'fechafin':fechafin})

  
        
    
    
#--------------------------------------------------------------------------------------------------------------------------------
@permission_required('cursos.view_curso', raise_exception=True)
@permission_required('cursos.change_curso', raise_exception=True)
@permission_required('cursos.delete_curso', raise_exception=True)
def estadoCursos(request):
    return render(request, 'cursos/estadoCursos.html', {'cursos': curso.objects.all()})
#------------------------------------------------------------------------------------------------------
@permission_required('cursos.add_inscriptos',raise_exception=True)
def inscripcion(request):
    return render(request, 'cursos/inscripcion.html')




# ---------------------------------------------------------------------------------------------#
@permission_required('cursos.add_pagoefectivo', raise_exception=True)
@permission_required('cursos.add_pagotarjeta', raise_exception=True)
@permission_required('cursos.add_pagotarjeta', raise_exception=True)
def pago(request,pk):
    Curso = get_object_or_404(curso, pk=pk)
    return render(request, 'cursos/seleccionpago.html',{'curso':Curso})

@permission_required('cursos.add_pagoefectivo', raise_exception=True)
def C_pagoEfectivo(request,pk):
    Curso = get_object_or_404(curso, pk=pk)
    idinscripto = request.user.estudiante.id
    inscripto = get_object_or_404(Estudiante, pk=idinscripto)
    if (request.method == 'POST'):
        efectivo_form = efectivoForm(request.POST)
        if efectivo_form.is_valid():
            nuevo_pagoEfectivo = efectivo_form.save(commit=True)
            messages.success(request,
                             'Se ha agregado correctamente el pagoEfectivo {}'.format(nuevo_pagoEfectivo))
            return redirect(reverse('cursos:comprobante_pago', args={nuevo_pagoEfectivo.id}))
    else:
        efectivo_form = efectivoForm(initial={'curso': Curso.id,'importe':Curso.costo,'inscripto':inscripto.id})
    return render(request, 'cursos/pagoEfectivo.html', {'form': efectivo_form,'curso':Curso})


# ---------------------------------------------------------------Tarjeta_-------------------------------------
@permission_required('cursos.add_pagotarjeta', raise_exception=True)
def C_pagoTarjeta(request,pk):
    Curso = get_object_or_404(curso, pk=pk)
    idinscripto = request.user.estudiante.id
    inscripto = get_object_or_404(Estudiante, pk=idinscripto)
    if (request.method == 'POST'):
        tarjeta_form = tarjetaForm(request.POST)
        if tarjeta_form.is_valid():
            nuevo_pagoTarjeta = tarjeta_form.save(commit=True)
            messages.success(request,
                             'Se ha agregado correctamente el pagoTarjeta {}'.format(nuevo_pagoTarjeta))
            return redirect(reverse('cursos:comprobante_pagoT', args={nuevo_pagoTarjeta.id}))

src/apps/cursos/templates/cursos/comprobantePago.html
{% extends 'base/base.html' %}
{% block title %}Comprobante de pago{% endblock title %}
{% block titulo %}Comprobante de pago{% endblock titulo %}
{% block contenido %}


<div class="container">

    <fieldset style="text-align:center">
        <p>Nombre Completo: {{comprobante.inscripto.nombreyapellido}}</p>
        <p>DNI:{{comprobante.inscripto.dni}}</p>
        <p>Numero de recibo:{{comprobante.numRecibo}}</p>
        <p>Curso:{{comprobante.curso.nombrecurso}} </p>
        <p>Importe:{{comprobante.curso.costo}}</p>      
        <p>fecha:{{comprobante.fecha}}</p>
        <p>Descripcion:{{comprobante.descripcion}}</p>

    </fieldset>
</div>




{% endblock  %}

src/apps/cursos/templates/cursos/comprobantePagoB.html
{% extends 'base/base.html' %}
{% block title %}Comprobante de pago{% endblock title %}
{% block titulo %}Comprobante de pago{% endblock titulo %}
{% block contenido %}


<div class="container">

    <fieldset style="text-align:center">
        <p>Nombre Completo: {{comprobante.inscripto.nombreyapellido}}</p>
        <p>DNI:{{comprobante.inscripto.dni}}</p>
        <p>Numero de recibo:{{comprobante.numRecibo}}</p>
        <p>Curso:{{comprobante.curso.nombrecurso}} </p>
        <p>Importe:{{comprobante.curso.costo}}</p>      
        <p>fecha:{{comprobante.fecha}}</p>
        <p>Descripcion:{{comprobante.descripcion}}</p>

    </fieldset>
</div>




{% endblock  %}

src/apps/cursos/templates/cursos/comprobantePagoT.html
{% extends 'base/base.html' %}
{% block title %}Comprobante de pago{% endblock title %}
{% block titulo %}Comprobante de pago{% endblock titulo %}
{% block contenido %}


<div class="container">

    <fieldset style="text-align:center">
        <p>Nombre Completo: {{comprobante.inscripto.nombreyapellido}}</p>
        <p>DNI:{{comprobante.inscripto.dni}}</p>
        <p>Numero de recibo:{{comprobante.numRecibo}}</p>
        <p>Curso:{{comprobante.curso.nombrecurso}} </p>
        <p>Importe:{{comprobante.curso.costo}}</p>      
        <p>fecha:{{comprobante.fecha}}</p>
        <p>Descripcion:{{comprobante.descripcion}}</p>

    </fieldset>
</div>




{% endblock  %}

src/apps/cursos/templates/cursos/estadisticas.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Estadisticas{% endblock title %}
{% block titulo %}Estadisticas{% endblock titulo %}
{% block contenido %}


<div class="container">
    <h1>Estadisticas del sitio</h1>
    <img  class='img-fluid' src="{% static 'image/images.jpg' %}" alt="Estadisticas" height="200" width="400">
    {% comment %} <fieldset>
        <form action="{% url 'cursos:Estadistica1' %}" method="POST">
                        {% csrf_token %}
                        
                        <select name="id_curso" required="" id="id_curso">
                            <option value="" selected="">---------</option>
                            {% for curso in cursos %}
                            <option value="{{curso.id}}">{{curso.nombrecurso}}</option>
                            {% endfor %}
                        </select>
                        <input class="btn btn-dark border" type="submit" value="Estadisticas">
        </form>
    </fieldset> {% endcomment %}
    <fieldset>
        <a class="btn btn-dark border" href="{% url 'cursos:Estadistica1' %}">Estadistica Cantidad de Inscriptos por Curso</a>
        <a class="btn btn-dark border" href="{% url 'cursos:Estadistica2' %}">Estadistica Cantidad de Pagos</a>
        
        <form action="{% url 'cursos:Estadistica3' %}" method="post">
            
            <label for="anioinicio">Año inicio:</label>
            <input type="date" name="id_anioinicio">
            <label for="aniofin">Año fin:</label>
            <input type="date" name="id_aniofin">
            {% csrf_token %}
            <input class="btn btn-dark border" type="submit" value="Estadisticas">
        </form>
        

    </fieldset>
</div>


{% endblock contenido %}

src/apps/cursos/templates/cursos/estadisticascantinscriptos.html
{% extends 'base/base.html' %}
{% block title %}Estadisticas Inscriptos Curso{% endblock title %}
{% block titulo %}Estadisticas Inscriptos Curso{% endblock titulo %}
{% block contenido %}
  <fieldset>
    <table class="table-dark table-hover; table table-bordered"  >
        <thead>
            <tr >
                <th scope="col">Nombre Curso</th>
                <th scope="col">Cantidad Inscriptos</th>   
            </tr>
        </thead>
        <tbody>
           
                {% for curso in cursos %}
                    <tr>
                        <td scope="row">{{curso.nombrecurso}}</td>
                        <td scope="row">{{curso.cant}}</td>
                    </tr>
                {% endfor %}
               
        </tbody>
        </table>
  </fieldset>
{% endblock contenido %}

src/apps/cursos/templates/cursos/estadisticascantpago.html
{% extends 'base/base.html' %}
{% block title %}Estadisticas Inscriptos Curso{% endblock title %}
{% block titulo %}Estadisticas Inscriptos Curso{% endblock titulo %}
{% block contenido %}
  <fieldset>
    <table class="table-dark table-hover; table table-bordered"  >
        <thead>
            <tr >
                <th scope="col">Nombre Curso</th>
                <th scope="col">Cantidad Abonados</th>
                <th scope="col">Cantidad Deudores</th>   
            </tr>
        </thead>
        <tbody>
           
                {% for curso in cursos %}
                    <tr>
                        <td scope="row">{{curso.nombrecurso}}</td>
                        <td scope="row">{{curso.cantP}}</td>
                        <td scope="row">{{curso.cantD}}</td>
                    </tr>
                {% endfor %}
               
        </tbody>
        </table>
  </fieldset>
{% endblock contenido %}

src/apps/cursos/templates/cursos/estadoCursos.html
{% extends 'base/base.html' %}
{% block title %}Propuestas{% endblock title %}
{% block titulo %}Propuestas{% endblock titulo %}
{% block contenido %}
{% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success' %}  <div class="message" role="status">{{ message }}</div>{% endif %}
            {% if message.tags == 'error' %}  <div class="errors" role="alert">{{ message }}</div>{% endif %}
        {% endfor %}
{% endif %}    
<div class="container">
    <div class="table-responsive-lg">
      <table class="table-dark table-hover; table table-bordered"  >
        <thead>
          <tr >
            <th scope="col">Nombre Curso</th>
            <th scope="col">Docente</th>
            <th scope="col">Fecha Inicio</th>
            <th scope="col">Estado</th>
            <th scope="col">opc</th>
          </tr>
        </thead>  
        <tbody>
          {% for curso in cursos%}
            {% if curso.estadocurso == 'En Revision'%}
            <tr>
              <td scope="row"><a href="{% url 'cursos:curso_evaluar' curso.id %}">{{curso.nombrecurso}}</a></td>
              <td scope="row">
                <ul>
                    {% for docente in curso.docentecargo.all %}
                        <li>{{ docente.nombreyapellido }}</li>
                    {% endfor %}
                </ul>
              </td>
              <td scope="row">{{curso.fechaini}}</td>
              <td scope="row">{{curso.estadocurso}}</td>
              <td scope="row"><a href="{% url 'cursos:curso_evaluar' curso.id %}" class="btn btn-dark border" >Evaluar</a>  
                <form action="{% url 'cursos:curso_delete' %}" method="POST">
                  {% csrf_token %}
                  <input type="hidden" name="id_curso" value="{{ curso.id }}">
                  <input class="btn btn-dark border" type="submit" value="Eliminar" onclick="return confirm('¿Está seguro que desea eliminar el registro?');">
                </form>
              </td></tr>
            {% endif %}  
          {% endfor%}
        </tbody> 
      </table>
    </div>
  </div>   
  <!-- {{request.resolver_match.view_name}} -->
  
{% endblock contenido %}

 

src/apps/cursos/templates/cursos/listaAlumnos.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Listas de alumnos{% endblock title %}
{% block titulo %}Lista de alumnos del Curso: {{curso.nombrecurso}}{% endblock titulo %} 
{% block contenido  %}
{% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success' %}  <div class="message" role="status">{{ message }}</div>{% endif %}
            {% if message.tags == 'error' %}  <div class="errors" role="alert">{{ message }}</div>{% endif %}
        {% endfor %}
{% endif %} 
<div class="container">
        {% if perms.cursos.change_inscriptos %}
        {% endif %}
        <div class="table-responsive-lg">
            <table  class="table-dark table-hover; table table-bordered  table-sm  align-middle" >
                <thead >
                    <tr>
                        <th scope="col-3">Matricula</th>
                        <th scope="col-3">Nombre</th> 
                        <th scope="col-4">Nota 1</th>
                        <th scope="col">Nota 2</th>
                        <th scope="col">Nota 3</th>
                        <th scope="col">Asistencia(%)</th>
                        {% if perms.cursos.change_inscriptos %}
                            <th scope="col">Accion</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for alumno  in alumnos %}
                     
                        <tr>
                            <td scope="row" >{{alumno.inscripto.matricula}}</td>
                            <td scope="row">{{alumno.inscripto.nombreyapellido}}</td> 
                            <td scope="row">{{alumno.nota1}}</td>
                            <td scope="row">{{alumno.nota2}}</td>
                            <td scope="row">{{alumno.nota3}}</td>
                            <td scope="row">{{alumno.asistencia}}</td>
                            {% if perms.cursos.change_inscriptos %}
                            <td scope="row"><a href="{% url 'cursos:alumno' alumno.id  %}" class="btn btn-dark border" >Evaluar</a>
                            {% endif %} 
                        </tr>
                     
                                          
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock  %}    

src/apps/cursos/templates/cursos/listaCursosAnio.html
{% extends 'base/base.html' %}
{% block title %}Estadisticas Inscriptos Curso{% endblock title %}
{% block titulo %}Estadisticas Inscriptos Curso{% endblock titulo %}
{% block contenido %}


<div class="container">
    <fieldset>
    <p style="font-size: 8mm;font-weight: 700; background-color: rgba(173, 216, 230, 0.65);">Cantidad de cursos entre {{fechaini}} y {{fechafin}}</p> 
        <ul>
            {% for curso in intervalo %}
                <li style="font-size: 6mm;font-weight: 400" >{{curso.nombrecurso}}</li>
            {% endfor %}
        </ul>
    </fieldset>
</div>
    
{% comment %} 

<table class="table-dark table-hover; table table-bordered"  >
    <thead>
      <tr>
        <th></th>
        <th> </th>
        <th ></th>
        <th ></th>
        <th ></th>
      
         
      </tr>
    </thead>  
    <tbody>   
        <tr>
          <td ></td>
          
          <td ></td>
          <td ></td>
          <td ></td>
        
            
            
         
        </tr>

       
    </tbody> 
</table> {% endcomment %}

{% endblock %}

src/apps/cursos/templates/cursos/seleccionpago.html
{% extends 'base/base.html' %}
{% block title %}>Pago del curso{% endblock title %}
{% block titulo %}Pago del curso{% endblock titulo %}
{% block contenido %}

<ul>
    <li><a href="{% url 'cursos:pagoefectivo' curso.id %}">Contado</a></li>
    <li><a href="{% url 'cursos:pagotarjeta' curso.id %}">Tarjeta</a></li>
    <li><a href="{% url 'cursos:pagotransferencia'  curso.id %}">Transferencia</a></li>
</ul>

{% endblock %}